In [1]:
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers


In [3]:
import numpy as np

In [16]:
x_train = np.array([[0.0],[0.1],[0.2],[0.3],[0.4],[0.5],[0.6],[0.7],[0.8],[0.9]])
y_train = np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.99])

In [8]:
model = keras.Sequential()

In [54]:
model.add(keras.layers.Dense(10, activation = 'relu', input_shape = (x_train.shape[1],)))

In [55]:
model.add(keras.layers.Dense(15, activation = 'relu', input_shape = (x_train.shape[1],)))

In [56]:
model.add(keras.layers.Dense(1))

In [57]:
model.compile(optimizer = 'adam', loss = 'mse', metrics= ['mae'])

In [58]:
model.fit(x_train, y_train, epochs = 100, batch_size = 1, verbose = 0)

In [47]:
x_test = np.array([[0.05],[0.15],[0.25],[0.35],[0.45],[0.55],[0.65],[0.75],[0.85],[0.95]])

In [59]:
pred = model.predict(x_test)

In [49]:
pred

array([[0.14714924],
       [0.24501139],
       [0.34955972],
       [0.45270133],
       [0.55388653],
       [0.6522924 ],
       [0.7496444 ],
       [0.84587777],
       [0.9413078 ],
       [1.0338783 ]], dtype=float32)

In [50]:
for i in pred:
    print(i)
    

[0.14714924]
[0.24501139]
[0.34955972]
[0.45270133]
[0.55388653]
[0.6522924]
[0.7496444]
[0.84587777]
[0.9413078]
[1.0338783]


In [51]:
model.predict([0.3])


array([[0.4018638]], dtype=float32)

In [60]:
model.predict([0.6])

array([[0.7009334]], dtype=float32)